package gym.modelo.entidad;
// Generated 17/06/2015 09:54:57 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CategoriaContrato generated by hbm2java
 */
public class CategoriaContrato  implements java.io.Serializable {


     private String idCategoriaContrato;
     private String nombreCategoria;
     private int descuento;

    public CategoriaContrato() {
    }

	
    public CategoriaContrato(String idCategoriaContrato) {
        this.idCategoriaContrato = idCategoriaContrato;
    }
    public CategoriaContrato(String idCategoriaContrato, String nombreCategoria, int descuento) {
       this.idCategoriaContrato = idCategoriaContrato;
       this.nombreCategoria = nombreCategoria;
       this.descuento = descuento;
    }
   
    public String getIdCategoriaContrato() {
        return this.idCategoriaContrato;
    }
    
    public void setIdCategoriaContrato(String idCategoriaContrato) {
        this.idCategoriaContrato = idCategoriaContrato;
    }
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public int getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(int descuento) {
        this.descuento = descuento;
    }




}


