package gym.modelo.entidad;
// Generated 30/05/2015 09:23:09 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ContratoCliente generated by hbm2java
 */
public class ContratoCliente  implements java.io.Serializable {


     private String idContratoCliente;
     private String persona;
     private String tipoContrato;
     private String idUsuario;
     private String usuario;
     private String categoriaContrato;
     private int montoTotal;
     private Date fechaInicio;
     private Date fechaFin;
     private String estado;
     private Date fechaRegistro;
     private Set movimientos = new HashSet(0);

    public ContratoCliente() {
    }

    public String getIdContratoCliente() {
        return idContratoCliente;
    }

    public void setIdContratoCliente(String idContratoCliente) {
        this.idContratoCliente = idContratoCliente;
    }

    public String getPersona() {
        return persona;
    }

    public void setPersona(String persona) {
        this.persona = persona;
    }

    public String getTipoContrato() {
        return tipoContrato;
    }

    public void setTipoContrato(String tipoContrato) {
        this.tipoContrato = tipoContrato;
    }

    public String getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getCategoriaContrato() {
        return categoriaContrato;
    }

    public void setCategoriaContrato(String categoriaContrato) {
        this.categoriaContrato = categoriaContrato;
    }

    public int getMontoTotal() {
        return montoTotal;
    }

    public void setMontoTotal(int montoTotal) {
        this.montoTotal = montoTotal;
    }

    public Date getFechaInicio() {
        return fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public Date getFechaFin() {
        return fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    public Set getMovimientos() {
        return movimientos;
    }

    public void setMovimientos(Set movimientos) {
        this.movimientos = movimientos;
    }
    
    
	
   

}


