package gym.modelo.entidad;
// Generated 17/06/2015 09:54:57 AM by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private String idPersona;
     private String nombres;
     private String apellidos;
     private String dni;
     private String sexo;
     private String telefono;
     private String direccion;
     private Usuario usuario;

    public Persona() {
    }

	
    public Persona(String idPersona) {
        this.idPersona = idPersona;
    }
    public Persona(String idPersona, String nombres, String apellidos, String dni, String sexo, String telefono, String direccion, Usuario usuario) {
       this.idPersona = idPersona;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.dni = dni;
       this.sexo = sexo;
       this.telefono = telefono;
       this.direccion = direccion;
       this.usuario = usuario;
    }
   
    public String getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(String idPersona) {
        this.idPersona = idPersona;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


