package gym.modelo.entidad;
// Generated 17/06/2015 09:54:57 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TipoContrato generated by hbm2java
 */
public class TipoContrato  implements java.io.Serializable {


     private String idTipoContrato;
     private String nombre;
     private int numDias;

    public TipoContrato() {
    }

	
    public TipoContrato(String idTipoContrato) {
        this.idTipoContrato = idTipoContrato;
    }
    public TipoContrato(String idTipoContrato, String nombre, int numDias) {
       this.idTipoContrato = idTipoContrato;
       this.nombre = nombre;
       this.numDias = numDias;
    }
   
    public String getIdTipoContrato() {
        return this.idTipoContrato;
    }
    
    public void setIdTipoContrato(String idTipoContrato) {
        this.idTipoContrato = idTipoContrato;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getNumDias() {
        return this.numDias;
    }
    
    public void setNumDias(int numDias) {
        this.numDias = numDias;
    }




}


